### ISSUE TITLE
PLAYLIST DOWNLOAD ONLY?

### ISSUE THREAD

**Issue by immanuelgracious** [Kaplas85/youtube-music-downloader#1]
¿Por qué solo es posible descargar listas de reproducción con este script? sugeriría que también incluyeras descargas de canciones individuales porque no todo el mundo busca listas de reproducción en YouTube, Y también descarga videos y no audios, corríjalo también y también piense en agregar una barra de progreso

**Comment by Kaplas85** [comment]
¡Hola @immanuelgracious! El requerimiento que mencionaste es muy cierto. Ya está esa funcionalidad activa para poder descargar canciones individuales como playlists.

Saludos y gracias.
